-- Seed data for the database
INSERT INTO BOOKS (TITLE, QUANTITY) VALUES ('Harry Potter', 5);
INSERT INTO BOOKS (TITLE, QUANTITY) VALUES ('Lord of the Rings', 3);
INSERT INTO BOOKS (TITLE, QUANTITY) VALUES ('The Hobbit', 2);
INSERT INTO BOOKS (TITLE, QUANTITY) VALUES ('The Witcher', 1);
INSERT INTO BOOKS (TITLE, QUANTITY) VALUES ('The Bible', 1000);
INSERT INTO BOOKS (TITLE, QUANTITY) VALUES ('The Great Gatsby', 50);
INSERT INTO BOOKS (TITLE, QUANTITY) VALUES ('To Kill a Mockingbird', 10);
INSERT INTO BOOKS (TITLE, QUANTITY) VALUES ('1984', 1984);
INSERT INTO BOOKS (TITLE, QUANTITY) VALUES ('The Catcher in the Rye', 10);
INSERT INTO BOOKS (TITLE, QUANTITY) VALUES ('The Da Vinci Code', 5);

INSERT INTO USERS (FIRST_NAME, LAST_NAME) VALUES ('John', 'Doe');
INSERT INTO USERS (FIRST_NAME, LAST_NAME) VALUES ('Jane', 'Doe');
INSERT INTO USERS (FIRST_NAME, LAST_NAME) VALUES ('Alice', 'Smith');
INSERT INTO USERS (FIRST_NAME, LAST_NAME) VALUES ('Bob', 'Marley');
INSERT INTO USERS (FIRST_NAME, LAST_NAME) VALUES ('Charlie', 'Brown');
INSERT INTO USERS (FIRST_NAME, LAST_NAME) VALUES ('Janez', 'Novak');
INSERT INTO USERS (FIRST_NAME, LAST_NAME) VALUES ('Matjaž', 'Kralj');
INSERT INTO USERS (FIRST_NAME, LAST_NAME) VALUES ('Julij', 'Cezar');
INSERT INTO USERS (FIRST_NAME, LAST_NAME) VALUES ('Taylor', 'Swift');
INSERT INTO USERS (FIRST_NAME, LAST_NAME) VALUES ('Kanye', 'West');



